#!/bin/bash
# script generated by qiBuild
# run a gdbserver on the remote target

here=$(cd $(dirname $0) ; pwd)

if [ "$#" -lt "1" ] ; then
  echo "please specify the binary to run"
  exit 1
fi

binary=$1
shift 1
echo ""
echo "To connect to this gdbserver launch the following command in another terminal:"
echo "  /usr/bin/gdb -x "${here}/setup_target.gdb" "${here}/${binary}""
echo ""

echo ssh -p 22 192.168.1.102 -- gdbserver :2159 "dialog_test/${1}"
